GET http://localhost:5000/

###

POST http://localhost:5000/api/users/
Content-Type: application/json

{
    "first_name": "Divine",
    "last_name": "Iso",
    "gender": "m",
    "email": "drrowly@gmil.com",
    "password": "123456",
    "number": "09079417401"
}

###

GET http://localhost:5000/api/users/
Content-Type: application/json

{
    "first_name": "Divine",
    "last_name": "Iso",
    "gender": "m",
    "email": "test@gmil.com",
    "password": "1234567",
    "number": "09079417401"
}

###

PATCH http://localhost:5000/api/admin/updateUser/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IiIsImxhc3ROYW1lIjoiIiwiZW1haWwiOiJpc29AZ21haWwuY29tIiwibnVtYmVyIjoiMDkwNzk0MTc0MDEiLCJjcmVhdGVkX2F0IjoiMjAyMy0xMC0zMVQxMjo0MjozOS4wMDBaIiwiZ29vZ19yZWZyZXNoX3Rva2VuIjpudWxsLCJhY2Nlc3NfdG9rZW4iOm51bGwsInBsYW4iOm51bGwsInN0YXR1cyI6bnVsbCwic2Vzc2lvbl91cmkiOm51bGwsImNvdW50X3VwbG9hZHMiOjAsImJ5dGVzIF90b3RhbCI6bnVsbCwidXNlcl9pZCI6Ijg2MDJiNDJkLTU1OTUtNDlmOC04N2Q1LWMxZGIxOGVkOGNlZCIsInJvbGUiOiJhZG1pbiJ9LCJqdGkiOiI4NjAyYjQyZC01NTk1LTQ5ZjgtODdkNS1jMWRiMThlZDhjZWQiLCJpYXQiOjE2OTkxMzczMDMsImV4cCI6MTY5OTE0MDkwM30.aEjwBNKJnG-UzauvVb-BkRyzUFX1xCmmmwizBa7zqhY

{
    "id": "2",
    "first_name": "Divine",
    "last_name": "dane",
    "gender": "m",
    "email": "testupdate@gmil.com",
    "password": "1234567",
    "number": "09079417401"
}

###

GET http://localhost:5000/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0TmFtZSI6IkRpdmluZSIsImxhc3ROYW1lIjoiSXNvIiwiZ2VuZGVyIjoibSIsImVtYWlsIjoidGVzdEBnbWlsLmNvbSIsIm51bWJlciI6MjE0NzQ4MzY0NywiY3JlYXRlZF9hdCI6IjAwMDAtMDAtMDAgMDA6MDA6MDAiLCJnb29nX3JlZnJlc2hfdG9rZW4iOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6bnVsbCwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6bnVsbCwiYnl0ZXMgX3RvdGFsIjpudWxsLCJ1c2VyX2lkIjpudWxsfSwiaWF0IjoxNjk1Mzc5MDEzLCJleHAiOjE2OTUzODI2MTN9.yj6Jtw2KgdyjPGUnz8vhWcUE4o7hFQZO9ZuVgolIbvo
    
{    
    "first_name": "Divine",
    "last_name": "Iso",
    "gender": "m",
    "email": "test@gmil.com",
    "password": "1234567",
    "number": "09079417401"
}

###

DELETE http://localhost:5000/api/users/
Content-Type: application/json

{
    "id": "1",
    "first_name": "Divine",
    "last_name": "Iso",
    "gender": "m",
    "email": "test@gmil.com",
    "password": "1234567",
    "number": "09079417401"
}

###

POST http://13.60.11.19:5000/api/users/login
Content-Type: application/json
 
{
    "email": "rol@gmail.com",
    "password": "1111111"

}

###

POST http://13.60.11.19:5000/api/users
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0TmFtZSI6IkRpdmluZSIsImxhc3ROYW1lIjoiSXNvIiwiZ2VuZGVyIjoibSIsImVtYWlsIjoidGVzdEBnbWlsLmNvbSIsIm51bWJlciI6MjE0NzQ4MzY0NywiY3JlYXRlZF9hdCI6IjAwMDAtMDAtMDAgMDA6MDA6MDAiLCJnb29nX3JlZnJlc2hfdG9rZW4iOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6bnVsbCwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6bnVsbCwiYnl0ZXMgX3RvdGFsIjpudWxsLCJ1c2VyX2lkIjpudWxsfSwiaWF0IjoxNjk0MDIwMDQ3LCJleHAiOjE2OTQwMjM2NDd9.HySHe9tztCnRGzt0GrG_x6X-YCurjMXj7n2D8eT8Mlw

{
    "number": "09079417401",
    "first_name": "Divine",
    "last_name": "Iso",
    "email": "test7@gmil.com",
    "name": "ubong",
    "password": "CypherConcern@$9095",
    "passwordConfirmation": "CypherConcern@$9095"
}

###


POST http://localhost:5000/api/users/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0TmFtZSI6IkRpdmluZSIsImxhc3ROYW1lIjoiSXNvIiwiZ2VuZGVyIjoibSIsImVtYWlsIjoidGVzdEBnbWlsLmNvbSIsIm51bWJlciI6MjE0NzQ4MzY0NywiY3JlYXRlZF9hdCI6IjAwMDAtMDAtMDAgMDA6MDA6MDAiLCJnb29nX3JlZnJlc2hfdG9rZW4iOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6bnVsbCwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6bnVsbCwiYnl0ZXMgX3RvdGFsIjpudWxsLCJ1c2VyX2lkIjpudWxsfSwiaWF0IjoxNjk1Mzc5MDEzLCJleHAiOjE2OTUzODI2MTN9.yj6Jtw2KgdyjPGUnz8vhWcUE4o7hFQZO9ZuVgolIbvo

{
    "name": "test@gmil.com",
    "description": "ubong",
    "folder": "1234567",
    "subfolder": "1234567",
    "drive_email": "1234567",
    "record_id": "1234567",
    "user_id": "1234567"
}

###

GET http://localhost:5000/api/users/get/fuhzQWCIu
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0TmFtZSI6IkRpdmluZSIsImxhc3ROYW1lIjoiSXNvIiwiZ2VuZGVyIjoibSIsImVtYWlsIjoidGVzdEBnbWlsLmNvbSIsIm51bWJlciI6MjE0NzQ4MzY0NywiY3JlYXRlZF9hdCI6IjAwMDAtMDAtMDAgMDA6MDA6MDAiLCJnb29nX3JlZnJlc2hfdG9rZW4iOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6bnVsbCwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6bnVsbCwiYnl0ZXMgX3RvdGFsIjpudWxsLCJ1c2VyX2lkIjpudWxsfSwiaWF0IjoxNjk1Mzc5MDEzLCJleHAiOjE2OTUzODI2MTN9.yj6Jtw2KgdyjPGUnz8vhWcUE4o7hFQZO9ZuVgolIbvos


###

GET http://localhost:5000/api/google/speedlinkaccess
Content-Type: application/json



###
GET http://localhost:5000/api/app/getrecords
Content-Type: application/json,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjE0LCJmaXJzdE5hbWUiOiJEaXZpbmUiLCJsYXN0TmFtZSI6IklzbyIsImdlbmRlciI6Im0iLCJlbWFpbCI6ImRycm93bHlAZ21pbC5jb20iLCJudW1iZXIiOjIxNDc0ODM2NDcsImNyZWF0ZWRfYXQiOiIwMDAwLTAwLTAwIDAwOjAwOjAwIiwiZ29vZ19yZWZyZXNoX3Rva2VuIjpudWxsLCJhY2Nlc3NfdG9rZW4iOm51bGwsInBsYW4iOm51bGwsInN0YXR1cyI6bnVsbCwic2Vzc2lvbl91cmkiOm51bGwsImNvdW50X3VwbG9hZHMiOm51bGwsImJ5dGVzIF90b3RhbCI6bnVsbCwidXNlcl9pZCI6ImhhdXl1NyJ9LCJpYXQiOjE2OTYxNDM5NTIsImV4cCI6MTY5NjE0NzU1Mn0.wVDYXKZaumD854aRqmxRN3c7zD7Oyny9ZuUnOKJW698


###
GET http://localhost:5000/api/admin/getTotalAmount
Content-Type: application/json,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6ImRpdmluZWUiLCJsYXN0TmFtZSI6ImRldCIsImVtYWlsIjoiaXNvQGdtYWlsLmNvbSIsIm51bWJlciI6IjA5MDc5NDE3NDAxIiwiY3JlYXRlZF9hdCI6IjIwMjMtMTAtMzFUMTI6NDI6MzkuMDAwWiIsImdvb2dfcmVmcmVzaF90b2tlbiI6bnVsbCwiYWNjZXNzX3Rva2VuIjpudWxsLCJwbGFuIjpudWxsLCJzdGF0dXMiOm51bGwsInNlc3Npb25fdXJpIjpudWxsLCJjb3VudF91cGxvYWRzIjowLCJieXRlcyBfdG90YWwiOm51bGwsInVzZXJfaWQiOiI4NjAyYjQyZC01NTk1LTQ5ZjgtODdkNS1jMWRiMThlZDhjZWQiLCJyb2xlIjoiYWRtaW4ifSwianRpIjoiODYwMmI0MmQtNTU5NS00OWY4LTg3ZDUtYzFkYjE4ZWQ4Y2VkIiwiaWF0IjoxNjk4ODQ3NzM1LCJleHAiOjE2OTg4NTEzMzV9.aUBqpnA6Kiy0HaMscKv4FJG3JL6hIttaZEJa_nJWY1s

{
    "searchTerm": "trying this"
}

###
GET http://localhost:5000/api/users/logout
Content-Type: application/json,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6ImRpdmluZWUiLCJsYXN0TmFtZSI6ImRldCIsImVtYWlsIjoiaXNvQGdtYWlsLmNvbSIsIm51bWJlciI6IjA5MDc5NDE3NDAxIiwiY3JlYXRlZF9hdCI6IjIwMjMtMTAtMzFUMTI6NDI6MzkuMDAwWiIsImdvb2dfcmVmcmVzaF90b2tlbiI6bnVsbCwiYWNjZXNzX3Rva2VuIjpudWxsLCJwbGFuIjpudWxsLCJzdGF0dXMiOm51bGwsInNlc3Npb25fdXJpIjpudWxsLCJjb3VudF91cGxvYWRzIjowLCJieXRlcyBfdG90YWwiOm51bGwsInVzZXJfaWQiOiI4NjAyYjQyZC01NTk1LTQ5ZjgtODdkNS1jMWRiMThlZDhjZWQiLCJyb2xlIjoiYWRtaW4ifSwianRpIjoiODYwMmI0MmQtNTU5NS00OWY4LTg3ZDUtYzFkYjE4ZWQ4Y2VkIiwiaWF0IjoxNjk4ODQ3NzM1LCJleHAiOjE2OTg4NTEzMzV9.aUBqpnA6Kiy0HaMscKv4FJG3JL6hIttaZEJa_nJWY1s

###

GET http://localhost:5000/testcon
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0TmFtZSI6IkRpdmluZSIsImxhc3ROYW1lIjoiSXNvIiwiZ2VuZGVyIjoibSIsImVtYWlsIjoidGVzdEBnbWlsLmNvbSIsIm51bWJlciI6MjE0NzQ4MzY0NywiY3JlYXRlZF9hdCI6IjAwMDAtMDAtMDAgMDA6MDA6MDAiLCJnb29nX3JlZnJlc2hfdG9rZW4iOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6bnVsbCwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6bnVsbCwiYnl0ZXMgX3RvdGFsIjpudWxsLCJ1c2VyX2lkIjpudWxsfSwiaWF0IjoxNjk0MDIwMDQ3LCJleHAiOjE2OTQwMjM2NDd9.HySHe9tztCnRGzt0GrG_x6X-YCurjMXj7n2D8eT8Mlw

###
POST http://localhost:5000/api/app/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0bmFtZSI6IkRpdmluZSIsImxhc3RuYW1lIjoiSXNvIiwiZW1haWwiOiJyb2xAZ21haWwuY29tIiwibnVtYmVyIjoiMDkwNzk0MTc0MDEiLCJjcmVhdGVkX2F0IjoiMjAyNC0wMy0wM1QwNzo0MjoxOS41OTlaIiwicmVjb3ZlcnlfaWQiOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6MSwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6MCwiYnl0ZXNfdG90YWwiOm51bGwsInVzZXJfaWQiOiJiYzFiNjVkMy1hZjU0LTQ5ZmYtYjM3Yi02ZTBkMThjNjBhYmQiLCJyb2xlIjoidXNlciIsIm5leHRfcGF5bWVudF9kYXRlIjpudWxsLCJ1cGRhdGVkX2F0IjpudWxsfSwianRpIjoiZmM0Yzc0MjRjMWU2OWIyMyIsImlhdCI6MTcxMDUwNDEzOCwiZXhwIjoxNzEwNTA3NzM4fQ.gGgu1v0Hie1QZJOTg6euWMQSnQqrkiDnYFJpMs49bMU

{
    "name": "test@gmil.com",
    "description": "ubong",
    "folder_id": "1234567",
    "subfolder": "1234567",
    "drive_email": "1234567",
    "preferred": "1",
    "user_id": "1234567"
}

###
GET http://localhost:5000/api/app/refresh
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0TmFtZSI6IkRpdmluZSIsImxhc3ROYW1lIjoiSXNvIiwiZ2VuZGVyIjoibSIsImVtYWlsIjoidGVzdEBnbWlsLmNvbSIsIm51bWJlciI6MjE0NzQ4MzY0NywiY3JlYXRlZF9hdCI6IjAwMDAtMDAtMDAgMDA6MDA6MDAiLCJnb29nX3JlZnJlc2hfdG9rZW4iOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6bnVsbCwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6bnVsbCwiYnl0ZXMgX3RvdGFsIjpudWxsLCJ1c2VyX2lkIjpudWxsfSwiaWF0IjoxNjk0MDIwMDQ3LCJleHAiOjE2OTQwMjM2NDd9.HySHe9tztCnRGzt0GrG_x6X-YCurjMXj7n2D8eT8Mlw

###

POST http://localhost:5000/api/users/forgot
Content-Type: application/json

{
    "email": "drrowly99@gmil.com"
}

# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0TmFtZSI6IkRpdmluZSIsImxhc3ROYW1lIjoiSXNvIiwiZ2VuZGVyIjoibSIsImVtYWlsIjoidGVzdEBnbWlsLmNvbSIsIm51bWJlciI6MjE0NzQ4MzY0NywiY3JlYXRlZF9hdCI6IjAwMDAtMDAtMDAgMDA6MDA6MDAiLCJnb29nX3JlZnJlc2hfdG9rZW4iOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6bnVsbCwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6bnVsbCwiYnl0ZXMgX3RvdGFsIjpudWxsLCJ1c2VyX2lkIjpudWxsfSwiaWF0IjoxNjk0MDIwMDQ3LCJleHAiOjE2OTQwMjM2NDd9.HySHe9tztCnRGzt0GrG_x6X-YCurjMXj7n2D8eT8Mlw

###


GET http://localhost:5000/api/users/verifyrecovery/5fb8c2c4-472f-4604-a50d-e5927c8a5eb60
Content-Type: application/json

###

POST http://localhost:5000/api/admin/changeUserPassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0bmFtZSI6IiIsImxhc3RuYW1lIjoiIiwiZW1haWwiOiJpc29AZ21haWwuY29tIiwibnVtYmVyIjoiMDkwNzk0MTc0MDEiLCJjcmVhdGVkX2F0IjoiMjAyMy0xMC0zMVQyMDo0MjozOS4wMDBaIiwicmVjb3ZlcnlfaWQiOiIyNGRiNzMyNi1mNGRlLTQwODEtOWViOC0zOGQxM2IwNWE2ZDgiLCJhY2Nlc3NfdG9rZW4iOm51bGwsInBsYW4iOjIsInN0YXR1cyI6IkFjdGl2ZSIsInNlc3Npb25fdXJpIjpudWxsLCJjb3VudF91cGxvYWRzIjowLCJieXRlc190b3RhbCI6bnVsbCwidXNlcl9pZCI6Ijg2MDJiNDJkLTU1OTUtNDlmOC04N2Q1LWMxZGIxOGVkOGNlZCIsInJvbGUiOiJhZG1pbiIsIm5leHRfcGF5bWVudF9kYXRlIjoiMjAyMy0xMS0xMVQxMzo1NjowMC4wMDBaIiwidXBkYXRlZF9hdCI6IjIwMjQtMDItMDhUMDk6Mzg6MTMuMzg5WiJ9LCJqdGkiOiI3YjQ4YWQxZTc3YTk0NzVhIiwiaWF0IjoxNzA5Mzk1MTQ0LCJleHAiOjE3MDkzOTg3NDR9.heJaLOfOPumXn9old24_VYtBEGrsxpLk0ASg8pnZLto

{
    "userEmail": "iso@gmail.com",
    "userPassword": "123456"
}

###
POST http://localhost:5000/api/users/setNewPassword 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0bmFtZSI6IiIsImxhc3RuYW1lIjoiIiwiZW1haWwiOiJpc29AZ21haWwuY29tIiwibnVtYmVyIjoiMDkwNzk0MTc0MDEiLCJjcmVhdGVkX2F0IjoiMjAyMy0xMC0zMVQyMDo0MjozOS4wMDBaIiwicmVjb3ZlcnlfaWQiOiIyNGRiNzMyNi1mNGRlLTQwODEtOWViOC0zOGQxM2IwNWE2ZDgiLCJhY2Nlc3NfdG9rZW4iOm51bGwsInBsYW4iOjIsInN0YXR1cyI6IkFjdGl2ZSIsInNlc3Npb25fdXJpIjpudWxsLCJjb3VudF91cGxvYWRzIjowLCJieXRlc190b3RhbCI6bnVsbCwidXNlcl9pZCI6Ijg2MDJiNDJkLTU1OTUtNDlmOC04N2Q1LWMxZGIxOGVkOGNlZCIsInJvbGUiOiJhZG1pbiIsIm5leHRfcGF5bWVudF9kYXRlIjoiMjAyMy0xMS0xMVQxMzo1NjowMC4wMDBaIiwidXBkYXRlZF9hdCI6IjIwMjQtMDItMDhUMDk6Mzg6MTMuMzg5WiJ9LCJqdGkiOiI3YjQ4YWQxZTc3YTk0NzVhIiwiaWF0IjoxNzA5Mzk1MTQ0LCJleHAiOjE3MDkzOTg3NDR9.heJaLOfOPumXn9old24_VYtBEGrsxpLk0ASg8pnZLto

{
    "oldPassword": "123456M",
    "newPassword": "123456"
}

###

POST http://localhost:5000/api/app/submitReplies
Content-Type: application/json

{
    "userEmail": "drrowly99@gmail.com",
    "userPassword": "123456"
}
###

GET http://localhost:5000/api/zoom/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0bmFtZSI6IkRpdmluZSIsImxhc3RuYW1lIjoiSXNvIiwiZW1haWwiOiJyb2xAZ21haWwuY29tIiwibnVtYmVyIjoiMDkwNzk0MTc0MDEiLCJjcmVhdGVkX2F0IjoiMjAyNC0wMy0wM1QwNzo0MjoxOS41OTlaIiwicmVjb3ZlcnlfaWQiOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6MSwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6MCwiYnl0ZXNfdG90YWwiOm51bGwsInVzZXJfaWQiOiJiYzFiNjVkMy1hZjU0LTQ5ZmYtYjM3Yi02ZTBkMThjNjBhYmQiLCJyb2xlIjoidXNlciIsIm5leHRfcGF5bWVudF9kYXRlIjpudWxsLCJ1cGRhdGVkX2F0IjpudWxsfSwianRpIjoiYmU0NjBmZGJkNDM2MTY0ZCIsImlhdCI6MTcwOTQ2NzA1NiwiZXhwIjoxNzA5NDcwNjU2fQ.x9ng6p2Tzj01XXEHBzbLtqtOCZT45cKD6Y1Cs_RTZec

###

POST http://localhost:5000/api/google/docToDrive
Content-Type: application/json

{
    "blob": "blob",
    "parents": "14dTWcAdet0GOuAi_KA9jUW0xn3LWkslM"
}
###

GET http://localhost:5000/api/google/downloadFolderAsZip/12/1ZdNsxYVgLUDo9_qCxTpNbF-EJpp3M0s_/rolandiso150@gmail.com
Content-Type: application/json

# {
#     "user_google_id": "12",
#     "folder": "1ZdNsxYVgLUDo9_qCxTpNbF-EJpp3M0s_",
#     "storage_email": "rolandiso150@gmail.com"
# }
###
GET http://localhost:5000/api/app/sendmail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0bmFtZSI6IkRpdmluZSIsImxhc3RuYW1lIjoiSXNvIiwiZW1haWwiOiJyb2xAZ21haWwuY29tIiwibnVtYmVyIjoiMDkwNzk0MTc0MDEiLCJjcmVhdGVkX2F0IjoiMjAyNC0wMy0wM1QwNzo0MjoxOS41OTlaIiwicmVjb3ZlcnlfaWQiOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6MSwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6MCwiYnl0ZXNfdG90YWwiOm51bGwsInVzZXJfaWQiOiJiYzFiNjVkMy1hZjU0LTQ5ZmYtYjM3Yi02ZTBkMThjNjBhYmQiLCJyb2xlIjoidXNlciIsIm5leHRfcGF5bWVudF9kYXRlIjpudWxsLCJ1cGRhdGVkX2F0IjpudWxsfSwianRpIjoiYmU0NjBmZGJkNDM2MTY0ZCIsImlhdCI6MTcwOTQ2NzA1NiwiZXhwIjoxNzA5NDcwNjU2fQ.x9ng6p2Tzj01XXEHBzbLtqtOCZT45cKD6Y1Cs_RTZec

###